### ISSUE TITLE
Searching for an invalid database.

### ISSUE THREAD

**Issue by Anuj16** [mik3y/django-db-multitenant#2]
My settings.py is something like this:

DATABASES = {
    'default': {
        'ENGINE': 'db_multitenant.db.backends.mysql',
        'NAME': 'test',
        'USER': '****_',
        'PASSWORD': '**_**',
        'HOST': '/Applications/MAMP/tmp/mysql/mysql.sock',
        'PORT': '3306',
    }
}

But its giving me the error 
"OperationalError at /admin/
(1049, "Unknown database 'tenant-localhost'")"

I guess it should search for the "test" database, but its not.
Can you guys please guide me to right direction.Thanks in advance.

**Comment by stephane** [comment]
@mik3y I think this issue could be closed...

**Comment by stephane** [comment]
Excepted with the PostgreSQL backend!
