### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by stephane** [mik3y/django-db-multitenant#21]
I have a few minor changes to apply to the documentation and some tests to pass before publishing a new release. In the meantime, could you give me the right to push a new release on Pypi or do you want to publish them?

My pypi account is `stephane`.

**Comment by stephane** [comment]
@mik3y any news on this?

**Comment by stephane** [comment]
ping @mik3y

**Comment by mik3y** [comment]
Sorry about that! I've added you to pypi 👍

**Comment by stephane** [comment]
Thank you

**Comment by stephane** [comment]
Done v0.3.2
https://pypi.python.org/pypi/django-db-multitenant
