### ISSUE TITLE
Conflict of licenses

### ISSUE THREAD

**Issue by stephane** [mik3y/django-db-multitenant#22]
The README states the project is under Apache 2 license but some files refer to 3-Clause BSD licence (such as utils.py).

Which is the license of the project?

**Comment by stephane** [comment]
@mik3y could I have your opinion on this?

**Comment by mik3y** [comment]
Oh, good catch! I'm fine with either, probably least confusing to make it Apache 2 all around?

Also - feel free to replace the copyright statements with something more general, like "Copyright (c) 2018 the contributors".

**Comment by stephane** [comment]
When I work on new open source project, as rule of thumb I use the license on the project I depend on (if any). What do you think about to use the Django license (BSD)?
https://github.com/django/django/blob/master/LICENSE

**Comment by mik3y** [comment]
Sure, that's fine foo.
