### ISSUE TITLE
Tenant after login

### ISSUE THREAD

**Issue by chesstrian** [mik3y/django-db-multitenant#9]
Hi @mik3y,

The requirement I'm trying to implement tells me that the tenant is known after a user is logged in, it means, the user table is shared or public and contains the tenant's name, and then we can have a different database per tenant.

Is this currently possible with your library?. Please give me some hints about implementing it if possible.

Thanks in advance.

**Comment by stephane** [comment]
It will be possible to do my PR#13 but you'll need to provide a custom authentication and not sure it will be easy to handle migration. You could also have a look to https://github.com/Corvia/django-tenant-users
